set(_CATKIN_CURRENT_PACKAGE "correspondence_grouping")
set(correspondence_grouping_VERSION "0.0.0")
set(correspondence_grouping_MAINTAINER "totallybobdavis <totallybobdavis@todo.todo>")
set(correspondence_grouping_PACKAGE_FORMAT "1")
set(correspondence_grouping_BUILD_DEPENDS )
set(correspondence_grouping_BUILD_EXPORT_DEPENDS )
set(correspondence_grouping_BUILDTOOL_DEPENDS "catkin")
set(correspondence_grouping_BUILDTOOL_EXPORT_DEPENDS )
set(correspondence_grouping_EXEC_DEPENDS )
set(correspondence_grouping_RUN_DEPENDS )
set(correspondence_grouping_TEST_DEPENDS )
set(correspondence_grouping_DOC_DEPENDS )
set(correspondence_grouping_DEPRECATED "")